pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Backend Developer Branch') {
            when {
                branch 'BackendEngineer'
            }
            steps {
                echo 'Backend developer branch build is running.'
                bat 'dir'
            }
        }

        stage('Deployment Branch') {
            when {
                branch 'Deployment-1'
            }
            steps {
                echo 'deployment branch validation is running.'
                bat 'dir'
            }
        }

        stage('Main Branch') {
            when {
                branch 'main'
            }
            steps {
                echo 'Main branch final integration is running.'
                bat 'dir'
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
